
pipeline {
    agent any
    stages {
        
        stage('Clonar repositorio') {
            steps {
                git branch: 'main', url: 'https://github.com/ivaneidepmn/tcc-ebac-projeto-final.git' 
            }
        }
        stage('Instalar dependencias necessarias') {
            steps {
                sh 'npm install'
            }
        }
        stage('Executar testes') {
            steps {
                sh ' NO_COLOR=1 npm run cy:run'
            }
        }
    }
    post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline succeeded.'clear
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
